bitnami/minideb

mkimage

Some licences require that the binaries be shipped with a copy
of the license. Debian does this in the copyright files in
/usr/share/doc. We need to leave those files there to keep
the image distributable.

Don't delete copyright files.

---

debootstrap/jessie
mkimage
test

sysv-rc and util-linux are used in the postinst scripts
of some packages, and so those packages won't install
if they aren't available.
sysv-rc contains update-rc.d, so any package that installs
a service would fail to install. Those packages are common
to install in to containers.
util-linux contains the getopt command which some scripts
expect to find.

Add some more commonly expected packages.

---

mkimage

Modifies the `install_packages` helper to use the --no-install-recommends flag by default.
Can be overridden by providing the `--install-recommends` to `install_packages`.

install_packages: use --no-install-recommends flag by default

---

README.md
mkimage

Sometimes apt will fail due a transient network issue. Often that
will be fixed by retrying.
This is particularly useful as part of an automated build pipeline.

Retry apt if it fails in `install_packages`.

---

mkimage
test

We were using a bashism in install_packages, but it was
a `/bin/sh` script. This meant there was a syntax error, but
it didn't kill the script so it would loop forever.
Add a test for the install_packages loop by installing something
that doesn't exist. This will trigger the loop, and should hit
the maximum loop count and error out. If it doesn't then the timeout
command will kill it and the test will fail. Using a timeout
isn't ideal, but better than looping forever.
Also clean up the test script a little bit and print a description
of each test before running it.

Fix the loop to be POSIX-compatible.

---

debootstrap/jessie
test

It's an essential package designed for exactly this.
It's pretty small, so not a huge cost to putting it back in.
The problem is pervasive enough, and it's unlikely that
users will know how to fix it, that it's worth us solving
it in the base image.
Fixes #17

Install ncurses-base to get terminfo files.

---

debootstrap/jessie
test

This is needed to install the mysql-server package. Fixes #16.

Install bsd utils to get `logger`

---

pushall

gcloud became more strict about separating gcloud arguments
from docker arguments, and is now throwing an error failing
the build https://travis-ci.org/bitnami/minideb/jobs/246281633#L5140
Use `--` to separate the arguments.

Fix arguments to `gcloud docker`

---

test

It seems like the build has been failing frequently
recently, apparently timing out during this test.
Increase the timeout to compensate.

Increase the timeout on the fail test

---

pushall

This patch uses a function from the [bitnami/test-infra](https://github.com/bitnami/test-infra) respository to update all the Bitnami base images that inherit from [bitnami/minideb](https://github.com/bitnami/minideb)
[bitnami/minideb-extras](https://github.com/bitnami/minideb-extras) and [bitnami/minideb-runtimes](https://github.com/bitnami/minideb-runtimes) for now.
Depends on bitnami/test-infra/pull/68

Update minideb-extras and minideb-runtimes each time minideb is pushed

---

.travis.yml

>The Ubuntu 16.04 server VM image apparently starts the "apt-daily.service" every 12 hours or so; this service performs various APT-related tasks like refreshing the list of available packages, performing unattended upgrades if needed, etc.
>When starting from a VM "snapshot", the service is triggered immediately, as (I presume) systemd realizes quickly that the timer should have gone off long ago.
See issue happening at https://api.travis-ci.org/v3/job/352495521/log.txt
Thread at:
https://github.com/travis-ci/travis-cookbooks/issues/952
Possible workaround applied at:
https://unix.stackexchange.com/questions/315502/how-to-disable-apt-daily-service-on-ubuntu-cloud-vm-image

Fix for Travis build failures due to running apt cron service

---

test

Since a few days ago the test `Check that install_packages doesn't loop forever on failures` is failing building minideb. Increasing the timeout just to discard network issues.

Increase test timeout

---

pushall

As we now are we building an additional minideb variant, we want update it on publish

add extras-base to the minideb derived list

---

pushall

This change enables Docker Content Trust for the tags being pushed.
I configured Travis to set the required key and passphrase.
Fixes #48.

Enable signing of images to push process

---

pushall

The code tries to avoid the contents to be printed in the output in case the shell tracing is enabled at some point, but that implementation also makes the `tmpdir` variable not to be accessible in that context.

Fix pushall script

---

pushall

We found this issue in the [travis-ci build](https://travis-ci.org/bitnami/minideb/jobs/430738346#L5162):
```
refusing to load key from /tmp/tmp.7IS3P9lCpg/key: private key file /tmp/tmp.7IS3P9lCpg/key must not be readable or writable by others
```
Making the file readable by the running user should fix the problem

fix key permissions

---

pushall

The docker content trust repository key is base64-encoded, so let's decode it before dumping it to a file

Decode key value

---

pushall

The result of pushing to GCR or Quay.io with content trust enabled is unknown, so I rather avoid it for now.

Enable content trust only when pushing to DockerHub

---

buildall

Buster is the latest Debian release, so point the `latest` tag to it.

Set buster as latest

---

buildall

When this happens in travis the intermediate images
aren't pushed, so you have to rebuild locally.
The dockerdiff output may be large, but that's more useful
than having to try and reproduce locally.

Include dockerdiff output in the log

---

buildall
buildone

This makes it easier to test all the code around the building
of an image as you can just build one image.

Split out a buildone script

---

mkimage
test

The builds were reproducible provided they were done on the same day.
However if they were done on different days they had different dates
in /etc/shadow and so changed. This meant that the images were
updated every day, and sometimes the reproducibility check would
fail if the day ticked over between the builds.

Fix reproducible builds by fixing date in /etc/shadow

---

mkimage

These depend on the build environment, but differences
don't show up inside the docker image as docker sets the
content of these files when starting a container.
We can put static values in the files to stop the image
layers differing without affecting the running containers
in any way.
This wasn't caught by the reproducibility check as the values
will be pretty static when built on the same host. (hostname
will be fixed, and resolv.conf will only change if the networking
configration changes enough, and that is unlikely to happen)

[mkimage] Clean hostname and resolv.conf

---

buildone

When I moved this code in to its own script, I moved it
out of a loop, so we can no longer `continue` and should
`return` instead.

[buildone] fix mistaken use of continue

---

mkimage

The httpredir.debian.org service has been dropped in favour of deb.debian.org
ref: https://lists.debian.org/debian-mirrors/2017/02/msg00000.html

Use deb.debian.org

---

buildone
pushall

Previously we were tagging for all registries as we built
the images and then pushing all registries blindly.
Now if an image hasn't changed it wouldn't tag with the other
registry tags, and then the push would fail as the gcr/quay
tags didn't exist.
Rather than taking care to tag in the case where the image
hasn't changed, instead change the pushall script to
only assume that `bitnami/minideb` tags are correct, and
tag the other registries based on that one before pushing.
This ensures that the tags will always exist, and also makes
sure we are pushing the same image to each registry (excluding
race conditions.)

Tag other registries in push

---

mkimage

/usr/share/doc contains a structure that might be like
```
foo/copyright
foo/other
bar -> foo
```
In this case we want to delete `foo/other`, but leave `bar` alone.
The previous code would delete `bar` as it is not a directory.
However, the structure of `/usr/share/doc` is such that the first
level is a per-package directory (or symlink) and the directory
contains the files. We therefore want to only consider files in the
package directories, so look a level further down the tree before
deleting.

Don't delete symlinks in /usr/share/doc

---

pushall

The -extras repos are archived, so we can't create PRs any more, so don't try.
-runtimes is still active.

Stop trying to update -extras

---

buildall

As previously researched in #86, there is some upstream issue with `util-linux` when building `unstable` distribution. 
This PR disable `minideb/unstable` building entry until the issue was solved so we can release the latest version for the rest of the distributions.

fix: disable unstable

---

pushall

Signed-off-by: darteaga <darteaga@vmware.com>
As previously researched in #86, there is some upstream issue with util-linux when building unstable distribution.
This PR disable minideb/unstable publishing entry until the issue was solved so we can release and publish the latest version for the rest of the distributions.

fix: not try to publish unstable distro

---

.gitignore
.travis.yml
Makefile
README.md
buildall
buildone
buildone_snapshot
import
install-qemu.sh
pushone
qemu_build
test

Related to #76 
I needed arm based images for one of my work, so I modified the build scripts to build and push multiarch images to docker hub.
I'm publishing my work as a draft hoping that could be useful to support arm64 architecture.
The trickiest part was to test the build on my local environment, so I wrote the `qemu_build` script that installs qemu requirements, downloads the ubuntu image for the target platform and executes a build inside an emulated environment. It than exports the images into a tar, transfers it from the vm to the local environment and imports it as docker image with the right tag.
The script is not intended to run on CI environment like travis, as without KVM the build is very slow, but could be useful to test multi arch builds in local environments, or test new …

arm64 support

---

.github/actions/build/action.yml
.github/workflows/main.yml
pushmanifest

This change includes Debian 11 (bullseye) as a platform to build, test and push automatically in our GitHub Actions

Include Debian 11 in CI automations

---

.github/actions/build/action.yml

Fix actual github actions for build arm64 bullseye image replacing old Groovy repository to use Hirsute version instead
**Benefits**
Keep image updated daily

Update build for arm64 bullseye

---

README.md

There are repeated reports that there are unfixed CVEs in minideb, but this
is due to Debian not releasing a DSA for that CVE. This tries to explain
that in the README for people to find or be pointed to.

Add note about security to the README

---

.github/actions/build/action.yml
.github/workflows/main.yml
README.md
buildall
pushall
pushmanifest
test

According to https://wiki.debian.org/LTS:
- Debian 8 Jessie is not supported since some time ago
- Debian 9 Stretch is going to be unsupported in 10 days
- Debian 10 Buster is going to be LTS
- Debian 11 Bullseye is the latest stable version
In this PR I am removing everything related to the deprecated versions (Debian 8 Jessie and Debian 9 Stretch) as well as converting Debian 11 Bullseye into the `latest`/default one

Update Debian versions

---

buildall
pushall
pushmanifest

Revert from #124 the changes related to using Debian 11 bullseye for the snapshot image. There is an issue when building this image (see [GH action](https://github.com/bitnami/minideb/runs/6966804999?check_suite_focus=true)):
```
================================
TEST: Checking that a package can be installed with apt
================================
Get:1 http://snapshot.debian.org/archive/debian/20220620T085218Z bullseye InRelease [116 kB]
Ign:2 http://snapshot.debian.org/archive/debian/20220620T085218Z bullseye-updates InRelease
Get:3 http://snapshot.debian.org/archive/debian-security/20220620T085218Z bullseye-security InRelease [44.1 kB]
Err:4 http://snapshot.debian.org/archive/debian/20220620T085218Z bullseye-updates Release
404  Not Found [IP: …
```

Use buster for minideb snapshot

---

.github/workflows/main.yml

The CI is failing because it assumes the snapshot image is the same as the latest one. This is not necessarily true, we can have an image marked as latest (bullseye) but a different one used for the snapshots (buster)

Allow snapshot image to be different as the latest one

---

install-qemu.sh

Changed libvirt-bin to libvirt-daemon-system libvirt-clients as
documented in https://lists.debian.org/debian-user/2016/11/msg00518.html
Signed-off-by: Bob Tanner <tanner@real-time.com>
Changed libvirt-bin to libvirt-daemon-system libvirt-clients as
documented in https://lists.debian.org/debian-user/2016/11/msg00518.html
**Benefits**
Lets the `qemu_build bullseye arm64` script install the correct libvirt packages. 
Assumes all the libvirt package are available for arm64 
**Additional information**
This PR only fixes the libvirt-bin package not being found. I do not know if this PR will allow a foreign architecture to be built.

WIP #129: Unable to build Minideb for ARM64 foreign architecture

---

.github/actions/build/action.yml
.github/workflows/main.yml

Update the GitHub Actions CI runners from Ubuntu 20.04 to 22.04 and remove the [workaround for installing a new enough version of qemu](https://github.com/bitnami/minideb/blame/32362b6/.github/actions/build/action.yml#L34). The version of qemu that comes with Ubuntu 22.04 is new enough that we no longer need that workaround.
CI builds and pushes to DockerHub succeed with this change.
Fixes #132. Builds were [failing](https://github.com/bitnami/minideb/runs/8027588256?check_suite_focus=true#step:3:167) because the CI job was trying to install qemu from the Ubuntu Hirsute repo, which [reached end-of-life](https://fridge.ubuntu.com/2022/01/21/ubuntu-21-04-hirsute-hippo-end-of-life-reached-on-january-20-2022/) and was finally deleted last month. The errors looked …

Update CI runners to Ubuntu 22.04 and remove workaround for qemu.

---

.github/workflows/triage.yml

Signed-off-by: Alejandro Gómez <morona@vmware.com>
Adding a new workflow to assign new (or reopened) issues/PRs to the Bitnami containers triage team.
**Benefits**
Bitnami team will be notified because team members will be assigned.
None detected.
**Applicable issues**
All new issues.

[bitnami/**] Adding the ability to assign to a team member of the containers triage

---

snapshot_id

Fixes the CI builds, whose error was being hidden by an incorrect output from the `snapshot_id` script.
**Benefits**
CI builds will succeed again
None
**Applicable issues**
N/A
**Additional information**
The script was extracting the URL query from the links on the main page, but the `&` character was URL encoded, which seems to have stopped working.

ci(snapshot_id): Fix URL escaping

---

.github/workflows/main.yml

As of now, we do not have any way to notify the team when a run of the CI Pipeline workflow fails so failures in it can be easily missed.
This PR adds the feature to notify when the CI Pipeline does not succeed via Slack. These notifications will be sent to a private Slack channel where every interested agent part of the "Fix build process" team is.
**Benefits**
Improves awareness of CI pipeline health and fixes its triggering condition.

[bitnami/*] ci: Configure Slack alerts for CI failures in bitnami/minideb

---

install-qemu.sh

replace `libvirt-bin` with `libvirt-daemon-system libvirt-clients` 
**Benefits**
No need to switch to an unstable source.
**Additional information**
Ref: https://wiki.debian.org/KVM#Installation
Packages: https://packages.debian.org/en/sid/libvirt-bin

refactor(qemu): improve qemu deps

---

mkimage

Remove extraneous device nodes
**Benefits**
There's no reason to ship them, the image will be smaller and compatible with ostree.
None
**Applicable issues**
Closes: https://github.com/bitnami/minideb/issues/171
**Additional information**
I didn't test this

mkimage: Remove device nodes

---

.github/workflows/main.yml

Make it so that only builds triggered by the `bitnami/minideb` repository will attempt to push images (because it is the only repository that has access to the required secrets). This will prevent builds in forked repositories that don't have access to the secrets from failing.

Only push images from bitnami/minideb repository

---

.github/workflows/main.yml

I'm assuming the scheduled jobs are mainly to keep the images up-to-date. For most repository forks there is no real need to run these builds on a schedule and just use up build resources necessarily.

Only run scheduled jobs on bitnami/minideb repo

---

.github/workflows/cd.yml
.github/workflows/ci.yml
pushmanifest
pushone

* Split the `main` workflow into `CI` and `CD` worklfows.
* Publish new minideb images in AWS ECR Public Gallery
**Benefits**
* Split workflow responsabilities to avoid the use of secrets in Pull request events. 
* Keep minideb image updated in AWS ECR gallery.
In case of error, we minideb image won't be published in DockerHub

feature(aws-gallery): Publish minideb images to AWS ECR public Gallery

---

README.md
import

**Build with podman**
This pull requests adds:
- a more generic approach to catch the hash from `load` command of docker/podman
- hints in the README, how to build with podman
**Benefits**
Daomonless build with **podman** as option to the build.
Not known.
**Applicable issues**
None.

Optional build with Podman
